# Generated by Django 2.2.5 on 2020-03-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trivia', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
