# Generated by Django 2.2.5 on 2020-03-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
