# Generated by Django 2.2.5 on 2020-03-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_statistics_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='content',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='trivia',
            new_name='name',
        ),
    ]
