# Generated by Django 2.2.5 on 2020-03-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('NS', 'news'), ('TM', 'tourism')], max_length=2),
        ),
    ]
