# Generated by Django 2.2.5 on 2020-03-18 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('head', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.TextField(max_length=250)),
                ('name', models.CharField(max_length=100)),
                ('barangay', models.CharField(choices=[('AN', 'Albagan'), ('BO', 'Buto'), ('DG', 'Danlag'), ('KG', 'Kipalbig'), ('LG', 'Lambayong'), ('LK', 'Lampitak'), ('LY', 'Liberty'), ('MA', 'Maltana'), ('P9', 'Palo 19'), ('PN', 'Poblacion'), ('PO', 'Pula Bato'), ('SO', 'San Isidro'), ('SZ', 'Sta Cruz'), ('TU', 'Tablu')], max_length=2)),
                ('contact', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.Office')),
            ],
        ),
    ]
