# Generated by Django 2.2.5 on 2020-03-23 06:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='annotate',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='transaction',
            field=models.TextField(help_text='Input your transaction. e.g. "Meeting po tayo, tungkol sa kaularan" Maximum of 3000 characters', max_length=250),
        ),
    ]
